### ISSUE TITLE
your indexed records for https://symbiota.ccber.ucsb.edu:443/collections/individual/index.php?occid=123814

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/ucsb-izc#4]
I was just looking at your GloBI indexed record at https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fucsb-izc&interactionType=interactsWith and I was wondering about ... (please add your own text)

and I would also like to have my specimens cited as @birdje requested for USNM https://github.com/globalbioticinteractions/usnm/issues/3 specimens.

Instead of the citation reading **https://symbiota.ccber.ucsb.edu:443/collections/individual/index.php?occid=123814**

I would like it to read **UCSB-IZC00024949 https://symbiota.ccber.ucsb.edu:443/collections/individual/index.php?occid=123814**

**Comment by jhpoelen** [comment]
@seltmann The proposed record citations are now available via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fucsb-izc&interactionType=interactsWith see attached screenshot - 

![Screenshot from 2022-01-26 11-45-36](https://user-images.githubusercontent.com/1084872/151235682-3c9a513f-73d6-4a4a-aa5a-7e336db69c02.png)

Previous the record was cited as:
```
https://symbiota.ccber.ucsb.edu:443/collections/individual/index.php?occid=234961 
```

now, as requested the record is cited as:

```
UCSB-IZC00043508 https://symbiota.ccber.ucsb.edu:443/collections/individual/index.php?occid=234961 
```
