### ISSUE TITLE
Review not working on ucsb-izc

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/ucsb-izc#5]
@jhpoelen adding an issue because the reviews of ucsb-izc are not running as expected

**Comment by jhpoelen** [comment]
@seltmann apologies for my delayed reply. Can you please be more specific about which reviews are not running as expected. Please note that Github automatically disables periodic reviews for inactive repositories.

**Comment by jhpoelen** [comment]
After manually re-enabling the UCSB IZC github action workflow, and after making some edits, the github action triggered data review appears to be running

![image](https://user-images.githubusercontent.com/1084872/199758148-45684583-a3bf-4b8f-b699-eb222b2d3cba.png)

Please feel free to re-open this issue or comment if you feel this issue needs more attention.
